import { FaYoutube, FaExclamation, FaUser, FaDollarSign } from "react-icons/fa";

export const menuItems = [
  {
    id: 1,
    title: "صفحه اصلی",
    link: "/",
    englishTitle: "/home",
  },
  {
    id: 2,
    title: "خدمات و ابزارها ",
    link: "/services",
    englishTitle: "services",
    children: [
      {
        id: 1,
        title: "افزونه TubeBuddy",
        desc: "خلاصه ای از توضیح این افزونه اینجاست",
        img: "tubebuddy.png",
        link: "/services/tubebuddy",
        englishTitle: "tubebuddy",
      },
      {
        id: 2,
        title: "افزونه Tube Ranker",
        desc: "خلاصه ای از توضیح این افزونه اینجاست",
        img: "tuberanker.png",
        link: "/services/tuberanker",
        englishTitle: "tuberanker",
      },
      {
        id: 3,
        title: "افزونه Unbox Social",
        desc: "خلاصه ای از توضیح این افزونه اینجاست",
        img: "unboxsocial.png",
        link: "/services/unboxsocial",
        englishTitle: "unboxsocial",
      },
      {
        id: 4,
        title: "افزونه Social Blade",
        desc: "خلاصه ای از توضیح این افزونه اینجاست",
        img: "socialblade.png",
        link: "/services/socialblade",
        englishTitle: "socialblade",
      },
      {
        id: 5,
        title: "افزونه VidIQ",
        desc: "خلاصه ای از توضیح این افزونه اینجاست",
        img: "vidiq.png",
        link: "/services/vidiq",
        englishTitle: "vidiq",
      },
    ],
  },
  {
    id: 3,
    title: "مشاوره",
    link: "/consultant",
    englishTitle: "consultant",
  },
  {
    id: 4,
    title: "تعرفه‌ها",
    link: "/prices",
    englishTitle: "prices",
  },
  {
    id: 5,
    title: "وبلاگ",
    link: "/blogs",
    englishTitle: "blogs",
  },
  {
    id: 6,
    title: "درباره‌ی ما",
    link: "/about-us",
    englishTitle: "about-us",
  },
];

export const footerItem = [
  {
    id: 1,
    title: "منوی سایت",
    children: [
      { id: 1, title: "صفحه اصلی", link: "/main", englishTitle: "main" },
      {
        id: 2,
        title: "مشاوره",
        link: "/consultant",
        englishTitle: "consultant",
      },
      {
        id: 3,
        title: "خدمات و ابزارها",
        link: "/services",
        englishTitle: "services",
      },
      { id: 4, title: "وبلاگ و مقالات", link: "/blogs", englishTitle: "blogs" },
      { id: 5, title: "تعرفه‌ها", link: "/prices", englishTitle: "prices" },
    ],
  },
  {
    id: 2,
    title: "ارتباط با ما",
    children: [
      {
        id: 1,
        title: "تماس با ما",
        link: "/contact-us",
        englishTitle: "contact-us",
      },
      { id: 2, title: "پشتیبانی", link: "/support", englishTitle: "support" },
      {
        id: 3,
        title: "درباره‌ی ما",
        link: "/about-us",
        englishTitle: "about-us",
      },
    ],
  },
  {
    id: 3,
    title: "صفحات دیگر",
    children: [
      {
        id: 1,
        title: "همکاری در فروش",
        link: "/participation",
        englishTitle: "participation",
      },
      { id: 2, title: "سوالات متداول", link: "/FAQ", englishTitle: "FAQ" },
      {
        id: 3,
        title: "توافق‌نامه کاربری",
        link: "/contract",
        englishTitle: "contract",
      },
      { id: 4, title: "شرایط و قوانین", link: "/terms", englishTitle: "terms" },
    ],
  },
];

export const cardItems = [
  {
    id: 1,
    title: "دلیل انتخاب ما",
    subTitle: "چرا یکتیــوبر را انتخاب کنیم؟",
    text: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد است.",
    style: "bg-orange-50",
    dotStyle: "bg-orange-200 text-orange-500",
    icon: FaExclamation,
  },
  {
    id: 2,
    title: "مشتریان ما",
    subTitle: "1200+",
    text: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان است",
    style: "bg-violet-50",
    dotStyle: "bg-violet-200 text-violet-500",
    icon: FaUser,
  },
  {
    id: 3,
    title: "درآمدها",
    subTitle: "$2,000",
    text: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان چاپگرها و متون بلکه روزنامه برای شرایط فعلی تکنولوژی مورد است.",
    style: "bg-rose-50",
    dotStyle: "bg-rose-200 text-rose-500",
    icon: FaDollarSign,
  },
];

export const featureItems = [
  {
    id: 1,
    title: "کارمزد منصفانه",
    img: "fee.png",
  },
  {
    id: 2,
    title: "تسویه سریع و به موقع",
    img: "cash.png",
  },
  {
    id: 3,
    title: "ارائه ابزارهای به روز",
    img: "ai.png",
  },
  {
    id: 4,
    title: "مانیتورینگ هوشمند کانال",
    img: "monitoring.png",
  },
  {
    id: 5,
    title: "حفاظت از کانال شما",
    img: "protect.png",
  },
];

export const formInputItems = [
  {
    id: 1,
    label: "نام و نام خانوادگی",
    placeholder: "نام خود را وارد کنید...",
    name: "name",
    style: "min-w-full md:min-w-1/2",
  },
  {
    id: 2,
    label: "شماره تماس",
    placeholder: "شماره تماس خود را وارد کنید...",
    name: "phone",
    style: "min-w-full md:min-w-1/2",
  },
  {
    id: 3,
    label: "لینک کانال یوتیوب",
    placeholder: "لینک کانال خود را وارد کنید...",
    name: "youtube",
    style: "min-w-full",
  },
];

export const sliderItems = [
  {
    id: 1,
    title: "ایده‌یابی و تولید محتوای جذاب",
    text: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است.",
    number: "3 / 1",
  },
  {
    id: 2,
    title: "ایده‌یابی و تولید محتوای جذاب",
    text: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است.",
    number: "3 / 2",
  },
  {
    id: 3,
    title: "ایده‌یابی و تولید محتوای جذاب",
    text: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است.",
    number: "3 / 3",
  },
];

export const userComments = [
  {
    id: 1,
    style: "bg-orange-50",
    user: "الهام محمدی",
    text: "تولید محتوا در یوتیوب یک فعالیت هیجان‌انگیز است که در کنار جذابیت‌هایش، مشکلات و فوت ‌و فن‌های خودش راهم دارد: از اینکه چطور محتوای مخاطب‌پسند تولید کنیم گرفته تا چه کارهایی باعث اخطار و استرایک گرفتن می‌شوند.",
    img: "elham.png",
  },
  {
    id: 2,
    style: "bg-rose-50",
    user: "حمید علیدوستی ",
    text: "تولید محتوا در یوتیوب یک فعالیت هیجان‌انگیز است که در کنار جذابیت‌هایش، مشکلات و فوت ‌و فن‌های خودش راهم دارد: از اینکه چطور محتوای مخاطب‌پسند تولید کنیم گرفته تا چه کارهایی باعث اخطار و استرایک گرفتن می‌شوند.",
    img: "hamid.png",
  },
  {
    id: 3,
    style: "bg-emerald-50",
    user: "نرگس بهرامی",
    text: "تولید محتوا در یوتیوب یک فعالیت هیجان‌انگیز است که در کنار جذابیت‌هایش، مشکلات و فوت ‌و فن‌های خودش راهم دارد: از اینکه چطور محتوای مخاطب‌پسند تولید کنیم گرفته تا چه کارهایی باعث اخطار و استرایک گرفتن می‌شوند.",
    img: "narges.png",
  },
];

export const blogItems = [
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "blogs",
    style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/1",
    createdAt: "2023-01-01",
    duration: "3",
    img: "/assets/images/blogs/blog1.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "help",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/2",
    createdAt: "2023-05-06",
    duration: "5",
    img: "/assets/images/blogs/blog2.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "help",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/3",
    createdAt: "2023-07-09",
    duration: "7",
    img: "/assets/images/blogs/blog3.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "analyze",
   style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/4",
    createdAt: "2023-04-17",
    duration: "4",
    img: "/assets/images/blogs/blog4.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "etc",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/5",
    createdAt: "2023-07-27",
    duration: "5",
    img: "/assets/images/blogs/blog5.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "etc",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/6",
    createdAt: "2023-07-09",
    duration: "7",
    img: "/assets/images/blogs/blog6.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "analyze",
    style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/7",
    createdAt: "2023-08-29",
    duration: "12",
    img: "/assets/images/blogs/blog7.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "grow",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/8",
    createdAt: "2023-04-19",
    duration: "10",
    img: "/assets/images/blogs/blog8.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "grow",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/9",
    createdAt: "2023-06-11",
    duration: "2",
    img: "/assets/images/blogs/blog9.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "blogs",
    style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/1",
    createdAt: "2023-01-01",
    duration: "3",
    img: "/assets/images/blogs/blog1.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "help",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/2",
    createdAt: "2023-05-06",
    duration: "5",
    img: "/assets/images/blogs/blog2.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "help",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/3",
    createdAt: "2023-07-09",
    duration: "7",
    img: "/assets/images/blogs/blog3.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "analyze",
   style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/4",
    createdAt: "2023-04-17",
    duration: "4",
    img: "/assets/images/blogs/blog4.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "etc",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/5",
    createdAt: "2023-07-27",
    duration: "5",
    img: "/assets/images/blogs/blog5.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "etc",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/6",
    createdAt: "2023-07-09",
    duration: "7",
    img: "/assets/images/blogs/blog6.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "analyze",
    style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/7",
    createdAt: "2023-08-29",
    duration: "12",
    img: "/assets/images/blogs/blog7.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "grow",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/8",
    createdAt: "2023-04-19",
    duration: "10",
    img: "/assets/images/blogs/blog8.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "grow",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/9",
    createdAt: "2023-06-11",
    duration: "2",
    img: "/assets/images/blogs/blog9.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "blogs",
    style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/1",
    createdAt: "2023-01-01",
    duration: "3",
    img: "/assets/images/blogs/blog1.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "help",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/2",
    createdAt: "2023-05-06",
    duration: "5",
    img: "/assets/images/blogs/blog2.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "help",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/3",
    createdAt: "2023-07-09",
    duration: "7",
    img: "/assets/images/blogs/blog3.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "analyze",
   style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/4",
    createdAt: "2023-04-17",
    duration: "4",
    img: "/assets/images/blogs/blog4.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "etc",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/5",
    createdAt: "2023-07-27",
    duration: "5",
    img: "/assets/images/blogs/blog5.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "etc",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/6",
    createdAt: "2023-07-09",
    duration: "7",
    img: "/assets/images/blogs/blog6.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "analyze",
    style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/7",
    createdAt: "2023-08-29",
    duration: "12",
    img: "/assets/images/blogs/blog7.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "grow",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/8",
    createdAt: "2023-04-19",
    duration: "10",
    img: "/assets/images/blogs/blog8.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "grow",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/9",
    createdAt: "2023-06-11",
    duration: "2",
    img: "/assets/images/blogs/blog9.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "blogs",
    style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/1",
    createdAt: "2023-01-01",
    duration: "3",
    img: "/assets/images/blogs/blog1.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "help",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/2",
    createdAt: "2023-05-06",
    duration: "5",
    img: "/assets/images/blogs/blog2.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "help",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/3",
    createdAt: "2023-07-09",
    duration: "7",
    img: "/assets/images/blogs/blog3.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "analyze",
   style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/4",
    createdAt: "2023-04-17",
    duration: "4",
    img: "/assets/images/blogs/blog4.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "etc",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/5",
    createdAt: "2023-07-27",
    duration: "5",
    img: "/assets/images/blogs/blog5.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "etc",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/6",
    createdAt: "2023-07-09",
    duration: "7",
    img: "/assets/images/blogs/blog6.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "analyze",
    style: "bg-violet-200 text-violet-500 hover:bg-violet-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/7",
    createdAt: "2023-08-29",
    duration: "12",
    img: "/assets/images/blogs/blog7.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "grow",
    style: "bg-red-100 text-red-500 hover:bg-red-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/8",
    createdAt: "2023-04-19",
    duration: "10",
    img: "/assets/images/blogs/blog8.png",
  },
  {
    id: crypto.randomUUID(),
    category: "مقاله آموزشی",
    englishTitle: "grow",
    style: "bg-amber-100 text-amber-500 hover:bg-amber-500 hover:text-white",
    title: "این یک متن تستی جهت نمایش مقاله است!",
    link: "/blog/9",
    createdAt: "2023-06-11",
    duration: "2",
    img: "/assets/images/blogs/blog9.png",
  },
];


export const filterTabItems = [
  { id: 1, title: "همه مقالات", englishTitle: "all" },
  { id: 2, title: "رشد در یوتیوب", englishTitle: "grow" },
  { id: 3, title: "آنالیز یوتیوب", englishTitle: "analyze" },
  { id: 4, title: "درهم برهم", englishTitle: "etc" },
  { id: 5, title: "راهنمای کسب درآمد", englishTitle: "help" },
  { id: 6, title: "مقالات آموزشی متفرقه", englishTitle: "blogs" },
];


export const formConsultantItems = [
  {
    id: 1,
    label: "نام و نام خانوادگی",
    placeholder: "نام خود را وارد کنید...",
    name: "name",
  },
  {
    id: 2,
    label: "شماره تماس",
    placeholder: "شماره تماس خود را وارد کنید...",
    name: "phone",
  },
  {
    id: 3,
    label: "آدرس ایمیل",
    placeholder: "آدرس ایمیل خود را وارد کنید...",
    name: "mail",
  },
  {
    id: 4,
    label: "لینک کانال یوتیوب",
    placeholder: "لینک کانال خود را وارد کنید...",
    name: "channelLink",
  },
  {
    id: 5,
    label: "نام کانال یوتیوب",
    placeholder: "نام کانال خود را وارد کنید....",
    name: "channelName",
  },
  {
    id: 6,
    label: "نام معرف (اختیاری)",
    placeholder: "نام معرف خود را وارد کنید...",
    name: "representative",
  },
];
