import type { Metadata } from "next";
import '../ui/styles/globals.css';
import Header from "@/ui/header";
import VazirFont from "@/ui/styles/fonts/fonts";
import Footer from "@/ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl" className="bg-white min-w-screen container max-w-screen-xl mx-auto">
      <body className={`${VazirFont.className}`}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
